# Generated by Django 5.2.16 on 2026-07-22 11:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_alter_faculty_options_faculty_faculty_type_and_more'),
        ('staff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_archived', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='В архиве')),
                ('archived_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата архивирования')),
                ('code', models.CharField(choices=[('system_admin', 'Администратор системы'), ('academic_office', 'Учебный отдел'), ('hr_officer', 'Кадровая служба'), ('dean_office', 'Деканат'), ('department_head', 'Заведующий кафедрой'), ('teacher', 'Преподаватель'), ('viewer', 'Наблюдатель')], db_index=True, max_length=50, unique=True, verbose_name='Код')),
                ('name_ru', models.CharField(max_length=255, verbose_name='Название на русском')),
                ('name_uz', models.CharField(max_length=255, verbose_name='Название на узбекском')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активна')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('archived_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL, verbose_name='Архивировал')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
            ],
            options={
                'verbose_name': 'Системная роль',
                'verbose_name_plural': 'Системные роли',
                'ordering': ('sort_order', 'name_ru'),
            },
        ),
        migrations.CreateModel(
            name='UserRoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_archived', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='В архиве')),
                ('archived_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата архивирования')),
                ('scope_type', models.CharField(choices=[('global', 'Вся система'), ('university', 'Университет'), ('faculty', 'Факультет'), ('department', 'Кафедра'), ('self', 'Только собственные данные')], db_index=True, default='self', max_length=20, verbose_name='Область действия')),
                ('valid_from', models.DateField(default=django.utils.timezone.localdate, verbose_name='Действует с')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Действует до')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активно')),
                ('notes', models.TextField(blank=True, verbose_name='Примечание')),
                ('archived_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL, verbose_name='Архивировал')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='role_assignments', to='organizations.department', verbose_name='Кафедра')),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='role_assignments', to='organizations.faculty', verbose_name='Факультет')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_assignments', to='access_control.systemrole', verbose_name='Роль')),
                ('staff_member', models.ForeignKey(blank=True, help_text='Используется для персональной роли преподавателя.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='role_assignments', to='staff.staffmember', verbose_name='Сотрудник')),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='role_assignments', to='organizations.university', verbose_name='Университет')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Назначение роли',
                'verbose_name_plural': 'Назначения ролей',
                'ordering': ('user', 'role__sort_order', 'scope_type'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_archived', False)), fields=('user', 'role', 'scope_type', 'university', 'faculty', 'department', 'staff_member'), name='unique_active_user_role_scope')],
            },
        ),
    ]
