# Generated by Django 5.2.16 on 2026-09-09 06:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_archived', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='В архиве')),
                ('archived_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата архивирования')),
                ('code', models.CharField(choices=[('system_admin', 'Администратор системы'), ('academic_office', 'Учебный отдел'), ('hr_officer', 'Кадровая служба'), ('dean_office', 'Деканат'), ('department_head', 'Заведующий кафедрой'), ('teacher', 'Преподаватель'), ('viewer', 'Наблюдатель')], db_index=True, max_length=50, unique=True, verbose_name='Код')),
                ('name_ru', models.CharField(max_length=255, verbose_name='Название на русском')),
                ('name_uz', models.CharField(max_length=255, verbose_name='Название на узбекском')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активна')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Системная роль',
                'verbose_name_plural': 'Системные роли',
                'ordering': ('sort_order', 'name_ru'),
            },
        ),
        migrations.CreateModel(
            name='UserRoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_archived', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='В архиве')),
                ('archived_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата архивирования')),
                ('scope_type', models.CharField(choices=[('global', 'Вся система'), ('university', 'Университет'), ('faculty', 'Факультет'), ('department', 'Кафедра'), ('self', 'Только собственные данные')], db_index=True, default='self', max_length=20, verbose_name='Область действия')),
                ('valid_from', models.DateField(default=django.utils.timezone.localdate, verbose_name='Действует с')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Действует до')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активно')),
                ('notes', models.TextField(blank=True, verbose_name='Примечание')),
            ],
            options={
                'verbose_name': 'Назначение роли',
                'verbose_name_plural': 'Назначения ролей',
                'ordering': ('user', 'role__sort_order', 'scope_type'),
            },
        ),
    ]
