# Generated by Django 5.2.16 on 2026-07-22 10:13

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('staff', '0001_initial'),
        ('workload', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_archived', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='В архиве')),
                ('archived_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата архивирования')),
                ('code', models.CharField(db_index=True, max_length=80, unique=True, verbose_name='Код')),
                ('name_ru', models.CharField(max_length=500, verbose_name='Название на русском')),
                ('name_uz', models.CharField(max_length=500, verbose_name='Название на узбекском')),
                ('default_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Рекомендуемые часы')),
                ('requires_evidence', models.BooleanField(default=False, verbose_name='Требуется подтверждение')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('archived_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL, verbose_name='Архивировал')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
            ],
            options={
                'verbose_name': 'Вид работы индивидуального плана',
                'verbose_name_plural': 'Виды работ индивидуального плана',
                'ordering': ('section__sort_order', 'sort_order', 'name_ru'),
            },
        ),
        migrations.CreateModel(
            name='IndividualPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_archived', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='В архиве')),
                ('archived_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата архивирования')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'Отправлен на рассмотрение'), ('returned', 'Возвращён на доработку'), ('approved', 'Утверждён'), ('in_progress', 'Выполняется'), ('completed', 'Завершён'), ('closed', 'Закрыт')], db_index=True, default='draft', max_length=20, verbose_name='Статус')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата утверждения')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата закрытия')),
                ('teacher_notes', models.TextField(blank=True, verbose_name='Примечание преподавателя')),
                ('reviewer_notes', models.TextField(blank=True, verbose_name='Комментарий проверяющего')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='individual_plans', to='academics.academicyear', verbose_name='Учебный год')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_individual_plans', to=settings.AUTH_USER_MODEL, verbose_name='Утвердил')),
                ('archived_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL, verbose_name='Архивировал')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('staff_employment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='individual_plans', to='staff.staffemployment', verbose_name='Трудовое назначение')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
            ],
            options={
                'verbose_name': 'Индивидуальный план',
                'verbose_name_plural': 'Индивидуальные планы',
                'ordering': ('-academic_year__start_year', 'staff_employment__staff_member__last_name'),
            },
        ),
        migrations.CreateModel(
            name='IndividualPlanSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_archived', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='В архиве')),
                ('archived_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата архивирования')),
                ('code', models.CharField(choices=[('teaching', 'Учебная работа'), ('methodological', 'Учебно-методическая работа'), ('scientific', 'Научная работа'), ('organizational', 'Организационная работа'), ('educational', 'Воспитательная работа'), ('professional_development', 'Повышение квалификации'), ('other', 'Другие виды работы')], max_length=40, unique=True, verbose_name='Код')),
                ('name_ru', models.CharField(max_length=255, verbose_name='Название на русском')),
                ('name_uz', models.CharField(max_length=255, verbose_name='Название на узбекском')),
                ('is_hourly', models.BooleanField(default=True, verbose_name='Учитывать часы')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('archived_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL, verbose_name='Архивировал')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
            ],
            options={
                'verbose_name': 'Раздел индивидуального плана',
                'verbose_name_plural': 'Разделы индивидуального плана',
                'ordering': ('sort_order', 'name_ru'),
            },
        ),
        migrations.CreateModel(
            name='IndividualPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_archived', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='В архиве')),
                ('archived_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата архивирования')),
                ('title', models.CharField(max_length=1000, verbose_name='Наименование работы')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('planned_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Плановые часы')),
                ('actual_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Фактические часы')),
                ('planned_start_date', models.DateField(blank=True, null=True, verbose_name='Плановая дата начала')),
                ('planned_end_date', models.DateField(blank=True, null=True, verbose_name='Плановая дата окончания')),
                ('actual_completion_date', models.DateField(blank=True, null=True, verbose_name='Дата фактического выполнения')),
                ('expected_result', models.TextField(blank=True, verbose_name='Ожидаемый результат')),
                ('actual_result', models.TextField(blank=True, verbose_name='Фактический результат')),
                ('evidence_url', models.URLField(blank=True, verbose_name='Ссылка на подтверждение')),
                ('evidence_document', models.CharField(blank=True, max_length=500, verbose_name='Реквизиты подтверждающего документа')),
                ('status', models.CharField(choices=[('planned', 'Запланирован'), ('in_progress', 'Выполняется'), ('completed', 'Выполнен'), ('confirmed', 'Подтверждён'), ('rejected', 'Не подтверждён'), ('cancelled', 'Отменён')], db_index=True, default='planned', max_length=20, verbose_name='Статус')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата подтверждения')),
                ('teacher_comment', models.TextField(blank=True, verbose_name='Комментарий преподавателя')),
                ('reviewer_comment', models.TextField(blank=True, verbose_name='Комментарий проверяющего')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('academic_semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='individual_plan_items', to='academics.academicsemester', verbose_name='Семестр выполнения')),
                ('activity_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plan_items', to='individual_plan.individualactivitytype', verbose_name='Вид работы')),
                ('archived_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL, verbose_name='Архивировал')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_individual_plan_items', to=settings.AUTH_USER_MODEL, verbose_name='Подтвердил')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('individual_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='individual_plan.individualplan', verbose_name='Индивидуальный план')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_items', to='individual_plan.individualplansection', verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'Пункт индивидуального плана',
                'verbose_name_plural': 'Пункты индивидуального плана',
                'ordering': ('section__sort_order', 'sort_order', 'planned_end_date', 'title'),
            },
        ),
        migrations.AddField(
            model_name='individualactivitytype',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activity_types', to='individual_plan.individualplansection', verbose_name='Раздел'),
        ),
        migrations.CreateModel(
            name='IndividualPlanTeachingWorkload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_archived', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='В архиве')),
                ('archived_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата архивирования')),
                ('imported_hours', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Импортированные часы')),
                ('archived_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL, verbose_name='Архивировал')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('plan_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_workload_link', to='individual_plan.individualplanitem', verbose_name='Пункт индивидуального плана')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
                ('workload_distribution', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='individual_plan_link', to='workload.workloaddistribution', verbose_name='Распределение учебной нагрузки')),
            ],
            options={
                'verbose_name': 'Учебная нагрузка индивидуального плана',
                'verbose_name_plural': 'Учебная нагрузка индивидуальных планов',
            },
        ),
        migrations.AddConstraint(
            model_name='individualplan',
            constraint=models.UniqueConstraint(condition=models.Q(('is_archived', False)), fields=('staff_employment', 'academic_year'), name='unique_employment_individual_plan_year'),
        ),
    ]
