# Generated by Django 5.2.16 on 2026-07-21 17:58

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('organizations', '0002_alter_faculty_options_faculty_faculty_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_archived', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='В архиве')),
                ('archived_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата архивирования')),
                ('code', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Код учебного плана')),
                ('version', models.PositiveSmallIntegerField(default=1, verbose_name='Номер версии')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('approved', 'Утверждён'), ('archived', 'Устаревшая версия')], db_index=True, default='draft', max_length=20, verbose_name='Статус')),
                ('approved_at', models.DateField(blank=True, null=True, verbose_name='Дата утверждения')),
                ('approval_document', models.CharField(blank=True, max_length=255, verbose_name='Документ утверждения')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('notes', models.TextField(blank=True, verbose_name='Примечание')),
                ('archived_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL, verbose_name='Архивировал')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('effective_academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='effective_curricula', to='academics.academicyear', verbose_name='Учебный год начала действия')),
                ('study_form', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='curricula', to='academics.studyform', verbose_name='Форма обучения')),
                ('study_program', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='curricula', to='academics.studyprogram', verbose_name='Направление обучения')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
            ],
            options={
                'verbose_name': 'Учебный план',
                'verbose_name_plural': 'Учебные планы',
                'ordering': ('-effective_academic_year__start_year', 'study_program__code', '-version'),
            },
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_archived', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='В архиве')),
                ('archived_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата архивирования')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Код дисциплины')),
                ('name_ru', models.CharField(max_length=500, verbose_name='Название на русском')),
                ('name_uz', models.CharField(max_length=500, verbose_name='Название на узбекском')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активна')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('archived_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL, verbose_name='Архивировал')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('default_department', models.ForeignKey(blank=True, help_text='Кафедра, которая обычно обеспечивает дисциплину. В конкретном учебном плане её можно изменить.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_disciplines', to='organizations.department', verbose_name='Кафедра по умолчанию')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
            ],
            options={
                'verbose_name': 'Дисциплина',
                'verbose_name_plural': 'Дисциплины',
                'ordering': ('sort_order', 'name_ru'),
            },
        ),
        migrations.CreateModel(
            name='CurriculumDiscipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_archived', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='В архиве')),
                ('archived_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата архивирования')),
                ('semester_number', models.PositiveSmallIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Номер семестра')),
                ('component_type', models.CharField(choices=[('required', 'Обязательная дисциплина'), ('elective', 'Дисциплина по выбору'), ('optional', 'Факультатив')], default='required', max_length=20, verbose_name='Компонент учебного плана')),
                ('control_form', models.CharField(choices=[('none', 'Без итогового контроля'), ('exam', 'Экзамен'), ('credit', 'Зачёт'), ('graded_credit', 'Дифференцированный зачёт'), ('course_work', 'Курсовая работа'), ('course_project', 'Курсовой проект')], default='none', max_length=20, verbose_name='Форма итогового контроля')),
                ('credits', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Количество кредитов')),
                ('total_academic_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Общий объём академических часов')),
                ('independent_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Часы самостоятельной работы')),
                ('weeks_count', models.PositiveSmallIntegerField(default=15, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество учебных недель')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активна')),
                ('notes', models.TextField(blank=True, verbose_name='Примечание')),
                ('archived_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL, verbose_name='Архивировал')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_disciplines', to='curriculum.curriculum', verbose_name='Учебный план')),
                ('teaching_department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='taught_curriculum_disciplines', to='organizations.department', verbose_name='Обеспечивающая кафедра')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='curriculum_entries', to='curriculum.discipline', verbose_name='Дисциплина')),
            ],
            options={
                'verbose_name': 'Дисциплина учебного плана',
                'verbose_name_plural': 'Дисциплины учебного плана',
                'ordering': ('curriculum', 'semester_number', 'discipline__name_ru'),
            },
        ),
        migrations.CreateModel(
            name='WorkloadType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_archived', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='В архиве')),
                ('archived_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата архивирования')),
                ('code', models.CharField(choices=[('lecture', 'Лекции'), ('practice', 'Практические занятия'), ('laboratory', 'Лабораторные занятия'), ('seminar', 'Семинарские занятия'), ('consultation', 'Консультации'), ('exam', 'Экзамен'), ('credit', 'Зачёт'), ('course_work', 'Курсовая работа'), ('course_project', 'Курсовой проект'), ('independent_work', 'Самостоятельная работа'), ('other', 'Другой вид работы')], max_length=40, unique=True, verbose_name='Код')),
                ('name_ru', models.CharField(max_length=255, verbose_name='Название на русском')),
                ('name_uz', models.CharField(max_length=255, verbose_name='Название на узбекском')),
                ('calculation_mode', models.CharField(choices=[('fixed', 'Фиксированные часы'), ('per_group', 'На учебную группу'), ('per_subgroup', 'На подгруппу'), ('per_student', 'На одного студента')], default='per_group', max_length=20, verbose_name='Способ расчёта по умолчанию')),
                ('is_classroom', models.BooleanField(default=True, verbose_name='Аудиторная работа')),
                ('is_teaching_load', models.BooleanField(default=True, verbose_name='Включать в нагрузку преподавателя')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('archived_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL, verbose_name='Архивировал')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
            ],
            options={
                'verbose_name': 'Вид учебной работы',
                'verbose_name_plural': 'Виды учебной работы',
                'ordering': ('sort_order', 'name_ru'),
            },
        ),
        migrations.CreateModel(
            name='CurriculumWorkload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_archived', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='В архиве')),
                ('archived_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата архивирования')),
                ('calculation_mode', models.CharField(choices=[('fixed', 'Фиксированные часы'), ('per_group', 'На учебную группу'), ('per_subgroup', 'На подгруппу'), ('per_student', 'На одного студента')], max_length=20, verbose_name='Способ расчёта')),
                ('base_hours', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Базовое количество часов')),
                ('students_per_unit', models.PositiveSmallIntegerField(blank=True, help_text='Используется для некоторых видов расчёта по количеству студентов.', null=True, verbose_name='Количество студентов на одну расчётную единицу')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активна')),
                ('notes', models.TextField(blank=True, verbose_name='Примечание')),
                ('archived_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL, verbose_name='Архивировал')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('curriculum_discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workload_items', to='curriculum.curriculumdiscipline', verbose_name='Дисциплина учебного плана')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
                ('workload_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='curriculum_workloads', to='curriculum.workloadtype', verbose_name='Вид учебной работы')),
            ],
            options={
                'verbose_name': 'Нагрузка дисциплины',
                'verbose_name_plural': 'Нагрузка дисциплин',
                'ordering': ('curriculum_discipline', 'workload_type__sort_order'),
            },
        ),
        migrations.AddConstraint(
            model_name='curriculum',
            constraint=models.UniqueConstraint(fields=('study_program', 'study_form', 'effective_academic_year', 'version'), name='unique_curriculum_version'),
        ),
        migrations.AddConstraint(
            model_name='curriculumdiscipline',
            constraint=models.UniqueConstraint(fields=('curriculum', 'discipline', 'semester_number'), name='unique_discipline_per_curriculum_semester'),
        ),
        migrations.AddConstraint(
            model_name='curriculumworkload',
            constraint=models.UniqueConstraint(fields=('curriculum_discipline', 'workload_type'), name='unique_workload_type_per_discipline'),
        ),
    ]
