# Generated by Django 5.2.16 on 2026-07-23 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workloadtype',
            name='report_category',
            field=models.CharField(choices=[('lecture', 'Лекции'), ('practice', 'Практические занятия'), ('laboratory', 'Лабораторные занятия'), ('course_work_supervision', 'Руководство курсовой работой'), ('course_project_supervision', 'Руководство курсовым проектом'), ('course_work_project_defense', 'Защита курсовой работы/проекта'), ('scientific_practice', 'Научная практика'), ('qualification_practice', 'Квалификационная практика'), ('master_dissertation_supervision', 'Руководство магистерской диссертацией'), ('master_dissertation_defense', 'Защита магистерской диссертации'), ('graduation_work_supervision', 'Руководство выпускной квалификационной работой'), ('graduation_work_defense', 'Защита выпускной квалификационной работы'), ('rating', 'Рейтинг'), ('other', 'Другое')], db_index=True, default='other', max_length=50, verbose_name='Категория для отчётов'),
        ),
    ]
