# Generated by Django 5.2.16 on 2026-08-16 13:22

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_add_workload_type_codes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='workloadtype',
            name='code',
            field=models.CharField(choices=[('lecture', 'Лекции'), ('practice', 'Практические занятия'), ('laboratory', 'Лабораторные занятия'), ('seminar', 'Семинарские занятия'), ('consultation', 'Консультации'), ('exam', 'Экзамен'), ('credit', 'Зачёт'), ('course_work', 'Курсовая работа'), ('course_project', 'Курсовой проект'), ('course_work_supervision', 'Руководство курсовой работой'), ('course_project_supervision', 'Руководство курсовым проектом'), ('course_work_project_defense', 'Защита курсовой работы/проекта'), ('scientific_practice', 'Научная практика'), ('qualification_practice', 'Квалификационная практика'), ('master_dissertation_supervision', 'Руководство магистерской диссертацией'), ('master_dissertation_defense', 'Защита магистерской диссертации'), ('graduation_work_supervision', 'Руководство выпускной квалификационной работой'), ('graduation_work_defense', 'Защита выпускной квалификационной работы'), ('rating', 'Рейтинг'), ('independent_work', 'Самостоятельная работа'), ('other', 'Другой вид работы')], max_length=40, unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='workloadtype',
            name='report_category',
            field=models.CharField(choices=[('lecture', 'Лекции'), ('practice', 'Практические занятия'), ('laboratory', 'Лабораторные занятия'), ('course_work_supervision', 'Руководство курсовой работой'), ('course_project_supervision', 'Руководство курсовым проектом'), ('course_work_defense', 'Защита курсовой работы'), ('course_project_defense', 'Защита курсовой проекта'), ('scientific_practice', 'Научная практика'), ('qualification_practice', 'Квалификационная практика'), ('master_dissertation_supervision', 'Руководство магистерской диссертацией'), ('master_dissertation_defense', 'Защита магистерской диссертации'), ('graduation_work_supervision', 'Руководство выпускной квалификационной работой'), ('graduation_work_defense', 'Защита выпускной квалификационной работы'), ('rating', 'Рейтинг'), ('other', 'Другое')], db_index=True, default='other', max_length=50, verbose_name='Категория для отчётов'),
        ),
        migrations.CreateModel(
            name='CurriculumWorkloadRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_archived', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='В архиве')),
                ('archived_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата архивирования')),
                ('calculation_mode', models.CharField(choices=[('fixed', 'Фиксированные часы'), ('per_group', 'На учебную группу'), ('per_subgroup', 'На подгруппу'), ('per_student', 'На одного студента')], max_length=20, verbose_name='Способ расчёта')),
                ('base_hours', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Базовое количество часов')),
                ('students_per_unit', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Количество студентов на одну расчётную единицу')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активна')),
                ('notes', models.TextField(blank=True, verbose_name='Примечание')),
                ('archived_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL, verbose_name='Архивировал')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workload_rules', to='curriculum.curriculum', verbose_name='Учебный план')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
                ('workload_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='curriculum_rules', to='curriculum.workloadtype', verbose_name='Вид учебной работы')),
            ],
            options={
                'verbose_name': 'Норма нагрузки учебного плана',
                'verbose_name_plural': 'Нормы нагрузки учебного плана',
                'ordering': ('curriculum', 'workload_type__sort_order'),
                'constraints': [models.UniqueConstraint(fields=('curriculum', 'workload_type'), name='unique_curriculum_workload_rule')],
            },
        ),
    ]
