# Generated by Django 5.2.16 on 2026-08-17 10:07

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_academicyear_closed_at_academicyear_closed_by_and_more'),
        ('curriculum', '0004_alter_workloadtype_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='workload_types',
            field=models.ManyToManyField(blank=True, help_text='Виды работы, которые могут использоваться для данной дисциплины в учебном плане.', related_name='disciplines', to='curriculum.workloadtype', verbose_name='Допустимые виды учебной работы'),
        ),
        migrations.AlterField(
            model_name='workloadtype',
            name='code',
            field=models.CharField(choices=[('lecture', 'Лекции'), ('practice', 'Практические занятия'), ('laboratory', 'Лабораторные занятия'), ('seminar', 'Семинарские занятия'), ('consultation', 'Консультации'), ('exam', 'Экзамен'), ('credit', 'Зачёт'), ('course_work', 'Курсовая работа'), ('course_project', 'Курсовой проект'), ('course_work_supervision', 'Руководство курсовой работой'), ('course_project_supervision', 'Руководство курсовым проектом'), ('course_work_defense', 'Защита курсовой работы'), ('course_project_defense', 'Защита курсового проекта'), ('course_work_project_defense', 'Защита курсовой работы/проекта'), ('scientific_practice_supervision', 'Руководство научной практикой'), ('qualification_practice_supervision', 'Руководство квалификационной практикой'), ('master_dissertation_supervision', 'Руководство магистерской диссертацией'), ('master_dissertation_defense', 'Защита магистерской диссертации'), ('graduation_work_supervision', 'Руководство выпускной квалификационной работой'), ('graduation_work_defense', 'Защита выпускной квалификационной работы'), ('rating', 'Рейтинг'), ('independent_work', 'Самостоятельная работа'), ('other', 'Другой вид работы')], max_length=40, unique=True, verbose_name='Код'),
        ),
        migrations.CreateModel(
            name='AcademicYearCreditNorm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_archived', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='В архиве')),
                ('archived_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата архивирования')),
                ('hours_per_credit', models.DecimalField(decimal_places=2, default=Decimal('30.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Количество часов в одном кредите')),
                ('notes', models.TextField(blank=True, verbose_name='Примечание')),
                ('academic_year', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_norm', to='academics.academicyear', verbose_name='Учебный год')),
                ('archived_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL, verbose_name='Архивировал')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
            ],
            options={
                'verbose_name': 'Норма академического кредита',
                'verbose_name_plural': 'Нормы академического кредита',
            },
        ),
        migrations.CreateModel(
            name='AcademicYearWorkloadNorm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_archived', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='В архиве')),
                ('archived_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата архивирования')),
                ('coefficient', models.DecimalField(decimal_places=4, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0000'))], verbose_name='Коэффициент / базовые часы')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активна')),
                ('notes', models.TextField(blank=True, verbose_name='Примечание')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_workload_norms', to='academics.academicyear', verbose_name='Учебный год')),
                ('archived_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL, verbose_name='Архивировал')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
                ('workload_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_year_norms', to='curriculum.workloadtype', verbose_name='Вид учебной работы')),
            ],
            options={
                'verbose_name': 'Норма учебной нагрузки',
                'verbose_name_plural': 'Нормы учебной нагрузки',
                'ordering': ('-academic_year__start_year', 'workload_type__sort_order'),
                'constraints': [models.UniqueConstraint(fields=('academic_year', 'workload_type'), name='unique_workload_norm_per_academic_year')],
            },
        ),
    ]
