# Generated by Django 5.2.16 on 2026-07-22 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('info', 'Информация'), ('success', 'Успешное действие'), ('warning', 'Предупреждение'), ('error', 'Ошибка'), ('reminder', 'Напоминание'), ('action_required', 'Требуется действие')], db_index=True, default='info', max_length=30, verbose_name='Тип')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('object_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='ID связанного объекта')),
                ('object_repr', models.CharField(blank=True, max_length=1000, verbose_name='Представление объекта')),
                ('action_url', models.CharField(blank=True, help_text='Внутренний маршрут frontend, например /individual-plans/15.', max_length=2000, verbose_name='Ссылка на действие')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные данные')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='Прочитано')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата прочтения')),
                ('is_archived', models.BooleanField(db_index=True, default=False, verbose_name='Архивировано')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата архивирования')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='contenttypes.contenttype', verbose_name='Тип связанного объекта')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created_at'], name='notification_recipient_idx'), models.Index(fields=['content_type', 'object_id'], name='notification_object_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('approve_individual_plan', 'Утвердить индивидуальный план'), ('review_individual_plan', 'Проверить индивидуальный план'), ('confirm_plan_item', 'Подтвердить выполнение пункта плана'), ('distribute_workload', 'Распределить учебную нагрузку'), ('approve_workload', 'Утвердить распределение нагрузки'), ('update_plan', 'Доработать индивидуальный план'), ('deadline_reminder', 'Напоминание о сроке'), ('other', 'Другая задача')], db_index=True, default='other', max_length=50, verbose_name='Тип задачи')),
                ('status', models.CharField(choices=[('open', 'Открыта'), ('in_progress', 'Выполняется'), ('completed', 'Выполнена'), ('cancelled', 'Отменена'), ('expired', 'Просрочена')], db_index=True, default='open', max_length=20, verbose_name='Статус')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('normal', 'Обычный'), ('high', 'Высокий'), ('urgent', 'Срочный')], db_index=True, default='normal', max_length=20, verbose_name='Приоритет')),
                ('title', models.CharField(max_length=500, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('object_id', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='ID связанного объекта')),
                ('object_repr', models.CharField(blank=True, max_length=1000, verbose_name='Представление объекта')),
                ('action_url', models.CharField(blank=True, max_length=2000, verbose_name='Ссылка на действие')),
                ('due_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Срок выполнения')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата начала')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата выполнения')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата отмены')),
                ('completion_comment', models.TextField(blank=True, verbose_name='Комментарий о выполнении')),
                ('cancellation_reason', models.TextField(blank=True, verbose_name='Причина отмены')),
                ('deduplication_key', models.CharField(blank=True, db_index=True, help_text='Используется для предотвращения повторного создания одинаковых открытых задач.', max_length=255, verbose_name='Ключ уникальности')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные данные')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_tasks', to='contenttypes.contenttype', verbose_name='Тип связанного объекта')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_user_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Задача пользователя',
                'verbose_name_plural': 'Задачи пользователей',
                'ordering': ('due_date', '-priority', '-created_at'),
                'indexes': [models.Index(fields=['assignee', 'status', 'due_date'], name='user_task_assignee_idx'), models.Index(fields=['content_type', 'object_id'], name='user_task_object_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deduplication_key__gt', ''), ('status__in', ('open', 'in_progress'))), fields=('assignee', 'deduplication_key'), name='unique_open_task_deduplication')],
            },
        ),
    ]
