# Generated by Django 5.2.16 on 2026-07-22 06:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('curriculum', '0001_initial'),
        ('organizations', '0002_alter_faculty_options_faculty_faculty_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupCurriculumAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_archived', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='В архиве')),
                ('archived_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата архивирования')),
                ('is_primary', models.BooleanField(db_index=True, default=True, verbose_name='Основной учебный план')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активно')),
                ('notes', models.TextField(blank=True, verbose_name='Примечание')),
                ('archived_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL, verbose_name='Архивировал')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_assignments', to='curriculum.curriculum', verbose_name='Учебный план')),
                ('end_academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ended_group_curricula', to='academics.academicyear', verbose_name='Учебный год окончания применения')),
                ('start_academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='started_group_curricula', to='academics.academicyear', verbose_name='Учебный год начала применения')),
                ('student_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='curriculum_assignments', to='academics.studentgroup', verbose_name='Учебная группа')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
            ],
            options={
                'verbose_name': 'Учебный план группы',
                'verbose_name_plural': 'Учебные планы групп',
                'ordering': ('-start_academic_year__start_year', 'student_group__code'),
            },
        ),
        migrations.CreateModel(
            name='GroupSemester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_archived', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='В архиве')),
                ('archived_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата архивирования')),
                ('semester_number', models.PositiveSmallIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Номер семестра по учебному плану')),
                ('students_count', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество студентов в семестре')),
                ('subgroup_count', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество подгрупп')),
                ('status', models.CharField(choices=[('planned', 'Запланирован'), ('active', 'Обучение идёт'), ('completed', 'Завершён'), ('cancelled', 'Отменён')], db_index=True, default='planned', max_length=20, verbose_name='Статус')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активно')),
                ('notes', models.TextField(blank=True, verbose_name='Примечание')),
                ('academic_semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_semesters', to='academics.academicsemester', verbose_name='Академический семестр')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_semesters', to='academics.academicyear', verbose_name='Учебный год')),
                ('archived_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL, verbose_name='Архивировал')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('group_curriculum', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_semesters', to='teaching.groupcurriculumassignment', verbose_name='Учебный план группы')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
            ],
            options={
                'verbose_name': 'Семестр учебной группы',
                'verbose_name_plural': 'Семестры учебных групп',
                'ordering': ('-academic_year__start_year', 'semester_number', 'group_curriculum__student_group__code'),
            },
        ),
        migrations.CreateModel(
            name='TeachingStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_archived', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='В архиве')),
                ('archived_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата архивирования')),
                ('code', models.CharField(db_index=True, max_length=100, verbose_name='Код потока')),
                ('name', models.CharField(max_length=255, verbose_name='Название потока')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('calculated', 'Нагрузка рассчитана'), ('approved', 'Утверждён'), ('cancelled', 'Отменён')], db_index=True, default='draft', max_length=20, verbose_name='Статус')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('notes', models.TextField(blank=True, verbose_name='Примечание')),
                ('academic_semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teaching_streams', to='academics.academicsemester', verbose_name='Академический семестр')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teaching_streams', to='academics.academicyear', verbose_name='Учебный год')),
                ('archived_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL, verbose_name='Архивировал')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('curriculum_discipline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teaching_streams', to='curriculum.curriculumdiscipline', verbose_name='Дисциплина учебного плана')),
                ('curriculum_workload', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teaching_streams', to='curriculum.curriculumworkload', verbose_name='Вид нагрузки дисциплины')),
                ('teaching_department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teaching_streams', to='organizations.department', verbose_name='Обеспечивающая кафедра')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
            ],
            options={
                'verbose_name': 'Учебный поток',
                'verbose_name_plural': 'Учебные потоки',
                'ordering': ('-academic_year__start_year', 'academic_semester__season', 'code'),
            },
        ),
        migrations.CreateModel(
            name='PlannedWorkload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_archived', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='В архиве')),
                ('archived_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата архивирования')),
                ('calculation_mode', models.CharField(choices=[('fixed', 'Фиксированные часы'), ('per_group', 'На учебную группу'), ('per_subgroup', 'На подгруппу'), ('per_student', 'На одного студента')], max_length=20, verbose_name='Способ расчёта')),
                ('base_hours', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Базовые часы')),
                ('calculation_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Расчётное количество')),
                ('total_hours', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Итоговые часы')),
                ('groups_count', models.PositiveSmallIntegerField(default=0, verbose_name='Количество групп')),
                ('subgroups_count', models.PositiveSmallIntegerField(default=0, verbose_name='Количество подгрупп')),
                ('students_count', models.PositiveIntegerField(default=0, verbose_name='Количество студентов')),
                ('status', models.CharField(choices=[('calculated', 'Рассчитана'), ('approved', 'Утверждена'), ('partially_distributed', 'Частично распределена'), ('distributed', 'Полностью распределена'), ('cancelled', 'Отменена')], db_index=True, default='calculated', max_length=30, verbose_name='Статус')),
                ('calculated_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время расчёта')),
                ('notes', models.TextField(blank=True, verbose_name='Примечание')),
                ('academic_semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planned_workloads', to='academics.academicsemester', verbose_name='Академический семестр')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planned_workloads', to='academics.academicyear', verbose_name='Учебный год')),
                ('archived_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL, verbose_name='Архивировал')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('curriculum_workload', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planned_workloads', to='curriculum.curriculumworkload', verbose_name='Вид нагрузки учебного плана')),
                ('teaching_department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planned_workloads', to='organizations.department', verbose_name='Обеспечивающая кафедра')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
                ('teaching_stream', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='planned_workload', to='teaching.teachingstream', verbose_name='Учебный поток')),
            ],
            options={
                'verbose_name': 'Плановая нагрузка',
                'verbose_name_plural': 'Плановая нагрузка',
                'ordering': ('-academic_year__start_year', 'teaching_department', 'teaching_stream__code'),
            },
        ),
        migrations.CreateModel(
            name='TeachingStreamGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_archived', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='В архиве')),
                ('archived_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата архивирования')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активно')),
                ('notes', models.TextField(blank=True, verbose_name='Примечание')),
                ('archived_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL, verbose_name='Архивировал')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('group_semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stream_memberships', to='teaching.groupsemester', verbose_name='Семестр учебной группы')),
                ('teaching_stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_groups', to='teaching.teachingstream', verbose_name='Учебный поток')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
            ],
            options={
                'verbose_name': 'Группа учебного потока',
                'verbose_name_plural': 'Группы учебного потока',
                'ordering': ('teaching_stream', 'group_semester__group_curriculum__student_group__code'),
            },
        ),
        migrations.AddField(
            model_name='teachingstream',
            name='group_semesters',
            field=models.ManyToManyField(related_name='teaching_streams', through='teaching.TeachingStreamGroup', to='teaching.groupsemester', verbose_name='Учебные группы'),
        ),
        migrations.AddConstraint(
            model_name='groupcurriculumassignment',
            constraint=models.UniqueConstraint(fields=('student_group', 'curriculum', 'start_academic_year'), name='unique_group_curriculum_assignment'),
        ),
        migrations.AddConstraint(
            model_name='groupcurriculumassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_archived', False), ('is_primary', True)), fields=('student_group',), name='unique_active_primary_group_curriculum'),
        ),
        migrations.AddConstraint(
            model_name='groupsemester',
            constraint=models.UniqueConstraint(fields=('group_curriculum', 'academic_year', 'semester_number'), name='unique_group_semester'),
        ),
        migrations.AddConstraint(
            model_name='teachingstreamgroup',
            constraint=models.UniqueConstraint(fields=('teaching_stream', 'group_semester'), name='unique_group_in_teaching_stream'),
        ),
        migrations.AddConstraint(
            model_name='teachingstream',
            constraint=models.UniqueConstraint(fields=('academic_year', 'academic_semester', 'code'), name='unique_teaching_stream_code'),
        ),
    ]
