# Generated by Django 5.2.16 on 2026-08-15 16:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_academicyear_closed_at_academicyear_closed_by_and_more'),
        ('curriculum', '0002_workloadtype_report_category'),
        ('organizations', '0002_alter_faculty_options_faculty_faculty_type_and_more'),
        ('teaching', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teachingstream',
            options={'ordering': ('-academic_year__start_year', 'academic_semester__season', 'curriculum__code', 'code'), 'verbose_name': 'Учебный поток', 'verbose_name_plural': 'Учебные потоки'},
        ),
        migrations.RemoveField(
            model_name='teachingstream',
            name='curriculum_discipline',
        ),
        migrations.RemoveField(
            model_name='teachingstream',
            name='curriculum_workload',
        ),
        migrations.RemoveField(
            model_name='teachingstream',
            name='teaching_department',
        ),
        migrations.AddField(
            model_name='teachingstream',
            name='curriculum',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='teaching_streams', to='curriculum.curriculum', verbose_name='Учебный план'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teachingstream',
            name='semester_number',
            field=models.PositiveSmallIntegerField(db_index=True, default='1', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Номер семестра по учебному плану'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='groupcurriculumassignment',
            name='curriculum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group_assignments', to='curriculum.curriculum', verbose_name='Учебный план'),
        ),
        migrations.AlterField(
            model_name='plannedworkload',
            name='teaching_stream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_workloads', to='teaching.teachingstream', verbose_name='Учебный поток'),
        ),
        migrations.AddConstraint(
            model_name='plannedworkload',
            constraint=models.UniqueConstraint(fields=('teaching_stream', 'curriculum_workload'), name='unique_stream_curriculum_workload'),
        ),
        migrations.AddConstraint(
            model_name='teachingstream',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_archived', False)), fields=('academic_year', 'academic_semester', 'curriculum', 'semester_number'), name='unique_active_curriculum_stream_semester'),
        ),
    ]
