# Generated by Django 5.2.16 on 2026-08-15 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_workloadtype_report_category'),
        ('teaching', '0002_alter_teachingstream_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupcurriculumassignment',
            name='curriculum',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, related_name='group_assignments', to='curriculum.curriculum', verbose_name='Учебный план'),
            preserve_default=False,
        ),
    ]
