# Generated by Django 5.2.16 on 2026-08-20 19:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_studentgroup_options_and_more'),
        ('curriculum', '0005_discipline_workload_types_alter_workloadtype_code_and_more'),
        ('organizations', '0002_alter_faculty_options_faculty_faculty_type_and_more'),
        ('teaching', '0003_alter_groupcurriculumassignment_curriculum'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='plannedworkload',
            name='unique_stream_curriculum_workload',
        ),
        migrations.AddField(
            model_name='groupsemester',
            name='weeks_count',
            field=models.PositiveSmallIntegerField(default=15, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество учебных недель'),
        ),
        migrations.AddField(
            model_name='plannedworkload',
            name='group_semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='planned_workloads', to='teaching.groupsemester', verbose_name='Семестр учебной группы'),
        ),
        migrations.AddConstraint(
            model_name='plannedworkload',
            constraint=models.UniqueConstraint(condition=models.Q(('group_semester__isnull', True)), fields=('teaching_stream', 'curriculum_workload'), name='unique_stream_level_workload'),
        ),
        migrations.AddConstraint(
            model_name='plannedworkload',
            constraint=models.UniqueConstraint(condition=models.Q(('group_semester__isnull', False)), fields=('teaching_stream', 'curriculum_workload', 'group_semester'), name='unique_group_level_workload'),
        ),
    ]
