# Generated by Django 5.2.16 on 2026-07-25 17:33

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('staff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffEmploymentAcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_archived', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='В архиве')),
                ('archived_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата архивирования')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('3.00'))], verbose_name='Размер ставки')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активно')),
                ('notes', models.TextField(blank=True, verbose_name='Примечание')),
                ('academic_degree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staff_academic_year_records', to='staff.academicdegree', verbose_name='Учёная степень')),
                ('academic_title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staff_academic_year_records', to='staff.academictitle', verbose_name='Учёное звание')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_employment_records', to='academics.academicyear', verbose_name='Учебный год')),
                ('archived_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL, verbose_name='Архивировал')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('staff_employment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_year_records', to='staff.staffemployment', verbose_name='Трудовое назначение')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
            ],
            options={
                'verbose_name': 'Кадровые данные преподавателя за учебный год',
                'verbose_name_plural': 'Кадровые данные преподавателей за учебные годы',
                'ordering': ('-academic_year__start_year', 'staff_employment__staff_member__last_name', 'staff_employment__staff_member__first_name'),
                'constraints': [models.UniqueConstraint(fields=('staff_employment', 'academic_year'), name='unique_staff_employment_academic_year')],
            },
        ),
    ]
