# Generated by Django 5.2.16 on 2026-07-22 06:09

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
        ('teaching', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkloadDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_archived', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='В архиве')),
                ('archived_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата архивирования')),
                ('allocated_hours', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Распределённые часы')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('approved', 'Утверждено'), ('cancelled', 'Отменено')], db_index=True, default='draft', max_length=20, verbose_name='Статус')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время утверждения')),
                ('notes', models.TextField(blank=True, verbose_name='Примечание')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_workload_distributions', to=settings.AUTH_USER_MODEL, verbose_name='Утвердил')),
                ('archived_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL, verbose_name='Архивировал')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('planned_workload', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distributions', to='teaching.plannedworkload', verbose_name='Плановая нагрузка')),
                ('staff_employment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workload_distributions', to='staff.staffemployment', verbose_name='Трудовое назначение преподавателя')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
            ],
            options={
                'verbose_name': 'Распределение нагрузки',
                'verbose_name_plural': 'Распределение нагрузки',
                'ordering': ('-planned_workload__academic_year__start_year', 'planned_workload__teaching_department__name_ru', 'staff_employment__staff_member__last_name'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_archived', False), ('status__in', ('draft', 'approved'))), fields=('planned_workload', 'staff_employment'), name='unique_active_workload_distribution'), models.CheckConstraint(condition=models.Q(('allocated_hours__gt', 0)), name='workload_distribution_hours_gt_zero')],
            },
        ),
    ]
