# Generated by Django 5.2.16 on 2026-07-22 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(db_index=True, max_length=100, verbose_name='ID объекта')),
                ('object_repr', models.CharField(blank=True, max_length=1000, verbose_name='Представление объекта')),
                ('action', models.CharField(choices=[('create', 'Создание'), ('update', 'Изменение'), ('status_change', 'Изменение статуса'), ('submit', 'Отправка на рассмотрение'), ('approve', 'Утверждение'), ('confirm', 'Подтверждение'), ('return', 'Возврат на доработку'), ('reject', 'Отклонение'), ('cancel', 'Отмена'), ('complete', 'Выполнение'), ('calculate', 'Расчёт'), ('distribute', 'Распределение'), ('import', 'Импорт'), ('archive', 'Архивирование'), ('restore', 'Восстановление'), ('delete', 'Удаление'), ('login', 'Вход в систему'), ('logout', 'Выход из системы'), ('other', 'Другое действие')], db_index=True, max_length=30, verbose_name='Действие')),
                ('action_label', models.CharField(blank=True, max_length=500, verbose_name='Описание действия')),
                ('old_values', models.JSONField(blank=True, default=dict, verbose_name='Старые значения')),
                ('new_values', models.JSONField(blank=True, default=dict, verbose_name='Новые значения')),
                ('changed_fields', models.JSONField(blank=True, default=list, verbose_name='Изменённые поля')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные данные')),
                ('reason', models.TextField(blank=True, verbose_name='Причина или комментарий')),
                ('actor_username', models.CharField(blank=True, max_length=255, verbose_name='Имя пользователя')),
                ('actor_full_name', models.CharField(blank=True, max_length=500, verbose_name='ФИО пользователя')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('user_agent', models.TextField(blank=True, verbose_name='User-Agent')),
                ('request_method', models.CharField(blank=True, max_length=20, verbose_name='HTTP-метод')),
                ('request_path', models.CharField(blank=True, max_length=2000, verbose_name='Путь запроса')),
                ('university_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True, verbose_name='ID университета')),
                ('faculty_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True, verbose_name='ID факультета')),
                ('department_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True, verbose_name='ID кафедры')),
                ('staff_member_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True, verbose_name='ID сотрудника')),
                ('academic_year_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True, verbose_name='ID учебного года')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата и время')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='contenttypes.contenttype', verbose_name='Тип объекта')),
            ],
            options={
                'verbose_name': 'Событие аудита',
                'verbose_name_plural': 'Журнал аудита',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['content_type', 'object_id', '-created_at'], name='audit_object_history_idx'), models.Index(fields=['actor', '-created_at'], name='audit_actor_history_idx'), models.Index(fields=['action', '-created_at'], name='audit_action_history_idx'), models.Index(fields=['department_id', '-created_at'], name='audit_department_idx'), models.Index(fields=['staff_member_id', '-created_at'], name='audit_staff_member_idx')],
            },
        ),
    ]
