# Generated by Django 5.2.16 on 2026-09-09 06:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicSemester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_archived', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='В архиве')),
                ('archived_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата архивирования')),
                ('season', models.CharField(choices=[('autumn', 'Осенний'), ('spring', 'Весенний')], max_length=10, verbose_name='Сезон')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('is_current', models.BooleanField(db_index=True, default=False, verbose_name='Текущий семестр')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Академический семестр',
                'verbose_name_plural': 'Академические семестры',
                'ordering': ('-academic_year__start_year', 'season'),
            },
        ),
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_archived', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='В архиве')),
                ('archived_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата архивирования')),
                ('start_year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2200)], verbose_name='Год начала')),
                ('end_year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2001), django.core.validators.MaxValueValidator(2201)], verbose_name='Год окончания')),
                ('is_current', models.BooleanField(db_index=True, default=False, verbose_name='Текущий учебный год')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('status', models.CharField(choices=[('open', 'Открыт'), ('closed', 'Закрыт')], db_index=True, default='open', max_length=20, verbose_name='Статус')),
                ('closed_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата закрытия')),
                ('closing_comment', models.TextField(blank=True, verbose_name='Комментарий при закрытии')),
                ('reopened_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата последнего открытия')),
                ('reopening_reason', models.TextField(blank=True, verbose_name='Причина повторного открытия')),
            ],
            options={
                'verbose_name': 'Учебный год',
                'verbose_name_plural': 'Учебные годы',
                'ordering': ('-start_year',),
            },
        ),
        migrations.CreateModel(
            name='EducationDuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_archived', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='В архиве')),
                ('archived_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата архивирования')),
                ('duration_months', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)], verbose_name='Продолжительность в месяцах')),
                ('semesters_count', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Количество семестров')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Продолжительность обучения',
                'verbose_name_plural': 'Продолжительность обучения',
                'ordering': ('education_level__sort_order', 'study_form__sort_order'),
            },
        ),
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_archived', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='В архиве')),
                ('archived_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата архивирования')),
                ('code', models.CharField(choices=[('bachelor', 'Бакалавриат'), ('master', 'Магистратура')], max_length=20, unique=True, verbose_name='Код')),
                ('name_ru', models.CharField(max_length=100, verbose_name='Название на русском')),
                ('name_uz', models.CharField(max_length=100, verbose_name='Название на узбекском')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активно')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Академическая степень',
                'verbose_name_plural': 'Академические степени',
                'ordering': ('sort_order', 'name_ru'),
            },
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_archived', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='В архиве')),
                ('archived_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата архивирования')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Код группы')),
                ('student_count', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1000)], verbose_name='Количество студентов')),
                ('subgroup_count', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Количество подгрупп')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активна')),
                ('notes', models.TextField(blank=True, verbose_name='Примечание')),
            ],
            options={
                'verbose_name': 'Учебная группа',
                'verbose_name_plural': 'Учебные группы',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='StudyForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_archived', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='В архиве')),
                ('archived_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата архивирования')),
                ('code', models.CharField(choices=[('full_time', 'Дневная'), ('part_time', 'Заочная'), ('evening', 'Вечерняя'), ('distance', 'Дистанционная')], max_length=20, unique=True, verbose_name='Код')),
                ('name_ru', models.CharField(max_length=100, verbose_name='Название на русском')),
                ('name_uz', models.CharField(max_length=100, verbose_name='Название на узбекском')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активно')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Форма обучения',
                'verbose_name_plural': 'Формы обучения',
                'ordering': ('sort_order', 'name_ru'),
            },
        ),
        migrations.CreateModel(
            name='StudyProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_archived', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='В архиве')),
                ('archived_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата архивирования')),
                ('code', models.CharField(db_index=True, max_length=50, verbose_name='Код направления')),
                ('name_ru', models.CharField(max_length=500, verbose_name='Название на русском')),
                ('name_uz', models.CharField(max_length=500, verbose_name='Название на узбекском')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активно')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Направление обучения',
                'verbose_name_plural': 'Направления обучения',
                'ordering': ('education_level__sort_order', 'code', 'name_ru'),
            },
        ),
    ]
