# Generated by Django 5.2.16 on 2026-07-29 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='closed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата закрытия'),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_academic_years', to=settings.AUTH_USER_MODEL, verbose_name='Закрыл'),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='closing_comment',
            field=models.TextField(blank=True, verbose_name='Комментарий при закрытии'),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='reopened_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата последнего открытия'),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='reopened_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reopened_academic_years', to=settings.AUTH_USER_MODEL, verbose_name='Повторно открыл'),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='reopening_reason',
            field=models.TextField(blank=True, verbose_name='Причина повторного открытия'),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='status',
            field=models.CharField(choices=[('open', 'Открыт'), ('closed', 'Закрыт')], db_index=True, default='open', max_length=20, verbose_name='Статус'),
        ),
    ]
