# Generated by Django 5.2.16 on 2026-09-09 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='academicsemester',
            name='archived_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL, verbose_name='Архивировал'),
        ),
        migrations.AddField(
            model_name='academicsemester',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AddField(
            model_name='academicsemester',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Изменил'),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='archived_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL, verbose_name='Архивировал'),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_academic_years', to=settings.AUTH_USER_MODEL, verbose_name='Закрыл'),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='reopened_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reopened_academic_years', to=settings.AUTH_USER_MODEL, verbose_name='Повторно открыл'),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Изменил'),
        ),
        migrations.AddField(
            model_name='academicsemester',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='semesters', to='academics.academicyear', verbose_name='Учебный год'),
        ),
        migrations.AddField(
            model_name='educationduration',
            name='archived_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL, verbose_name='Архивировал'),
        ),
        migrations.AddField(
            model_name='educationduration',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AddField(
            model_name='educationduration',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Изменил'),
        ),
        migrations.AddField(
            model_name='educationlevel',
            name='archived_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL, verbose_name='Архивировал'),
        ),
        migrations.AddField(
            model_name='educationlevel',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AddField(
            model_name='educationlevel',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Изменил'),
        ),
        migrations.AddField(
            model_name='educationduration',
            name='education_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='durations', to='academics.educationlevel', verbose_name='Академическая степень'),
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='academic_year_admission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admitted_groups', to='academics.academicyear', verbose_name='Учебный год поступления'),
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='archived_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL, verbose_name='Архивировал'),
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_groups', to='organizations.faculty', verbose_name='Факультет или отделение'),
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='graduation_academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='graduating_groups', to='academics.academicyear', verbose_name='Плановый учебный год выпуска'),
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Изменил'),
        ),
        migrations.AddField(
            model_name='studyform',
            name='archived_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL, verbose_name='Архивировал'),
        ),
        migrations.AddField(
            model_name='studyform',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AddField(
            model_name='studyform',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Изменил'),
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='study_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_groups', to='academics.studyform', verbose_name='Форма обучения'),
        ),
        migrations.AddField(
            model_name='educationduration',
            name='study_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='durations', to='academics.studyform', verbose_name='Форма обучения'),
        ),
        migrations.AddField(
            model_name='studyprogram',
            name='archived_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL, verbose_name='Архивировал'),
        ),
        migrations.AddField(
            model_name='studyprogram',
            name='created_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
        ),
        migrations.AddField(
            model_name='studyprogram',
            name='education_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='study_programs', to='academics.educationlevel', verbose_name='Академическая степень'),
        ),
        migrations.AddField(
            model_name='studyprogram',
            name='profiling_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profiled_study_programs', to='organizations.department', verbose_name='Профилирующая кафедра'),
        ),
        migrations.AddField(
            model_name='studyprogram',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='study_programs', to='organizations.university', verbose_name='Университет'),
        ),
        migrations.AddField(
            model_name='studyprogram',
            name='updated_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Изменил'),
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='study_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_groups', to='academics.studyprogram', verbose_name='Направление обучения'),
        ),
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=models.UniqueConstraint(fields=('start_year', 'end_year'), name='unique_academic_year_range'),
        ),
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=models.UniqueConstraint(condition=models.Q(('is_archived', False), ('is_current', True)), fields=('is_current',), name='unique_current_academic_year'),
        ),
        migrations.AddConstraint(
            model_name='academicsemester',
            constraint=models.UniqueConstraint(fields=('academic_year', 'season'), name='unique_season_per_academic_year'),
        ),
        migrations.AddConstraint(
            model_name='academicsemester',
            constraint=models.UniqueConstraint(condition=models.Q(('is_archived', False), ('is_current', True)), fields=('is_current',), name='unique_current_academic_semester'),
        ),
        migrations.AddConstraint(
            model_name='educationduration',
            constraint=models.UniqueConstraint(fields=('education_level', 'study_form'), name='unique_level_study_form_duration'),
        ),
        migrations.AddConstraint(
            model_name='studyprogram',
            constraint=models.UniqueConstraint(fields=('university', 'education_level', 'code'), name='unique_study_program_code'),
        ),
    ]
