# Generated by Django 5.2.16 on 2026-08-20 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_academicyear_closed_at_academicyear_closed_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentgroup',
            options={'ordering': ('code',), 'verbose_name': 'Учебная группа', 'verbose_name_plural': 'Учебные группы'},
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='academic_year_admission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admitted_groups', to='academics.academicyear', verbose_name='Учебный год поступления'),
        ),
    ]
