# Generated by Django 5.2.16 on 2026-07-23 06:50

import apps.reports.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_alter_faculty_options_faculty_faculty_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_archived', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='В архиве')),
                ('archived_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата архивирования')),
                ('template_type', models.CharField(choices=[('teacher_workload', 'Нагрузка преподавателя за учебный год'), ('department_workload', 'Общая нагрузка кафедры за учебный год')], db_index=True, max_length=50, verbose_name='Тип шаблона')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Версия')),
                ('file', models.FileField(upload_to=apps.reports.models.report_template_upload_to, verbose_name='Excel-файл')),
                ('sheet_name', models.CharField(blank=True, help_text='Если не указано, используется активный лист.', max_length=255, verbose_name='Название листа')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активен')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('archived_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL, verbose_name='Архивировал')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('university', models.ForeignKey(blank=True, help_text='Если университет не указан, шаблон является общим.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='excel_report_templates', to='organizations.university', verbose_name='Университет')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
            ],
            options={
                'verbose_name': 'Excel-шаблон отчёта',
                'verbose_name_plural': 'Excel-шаблоны отчётов',
                'ordering': ('template_type', '-version'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_archived', False), ('university__isnull', False)), fields=('university', 'template_type'), name='unique_active_excel_template'), models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_archived', False), ('university__isnull', True)), fields=('template_type',), name='unique_active_global_excel_template')],
            },
        ),
    ]
