# Generated by Django 5.2.16 on 2026-07-25 17:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_faculty_options_faculty_faculty_type_and_more'),
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='excelreporttemplate',
            name='unique_active_excel_template',
        ),
        migrations.AddConstraint(
            model_name='excelreporttemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_archived', False), ('university__isnull', False)), fields=('university', 'template_type'), name='unique_active_university_excel_template'),
        ),
    ]
