# Generated by Django 5.2.16 on 2026-07-20 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_archived', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='В архиве')),
                ('archived_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата архивирования')),
                ('code', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='Код')),
                ('name_ru', models.CharField(max_length=255, verbose_name='Название на русском')),
                ('name_uz', models.CharField(max_length=255, verbose_name='Название на узбекском')),
                ('short_name_ru', models.CharField(blank=True, max_length=100, verbose_name='Краткое название на русском')),
                ('short_name_uz', models.CharField(blank=True, max_length=100, verbose_name='Краткое название на узбекском')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активно')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('address_ru', models.CharField(blank=True, max_length=500, verbose_name='Адрес на русском')),
                ('address_uz', models.CharField(blank=True, max_length=500, verbose_name='Адрес на узбекском')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Электронная почта')),
                ('website', models.URLField(blank=True, verbose_name='Веб-сайт')),
                ('archived_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL, verbose_name='Архивировал')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
            ],
            options={
                'verbose_name': 'Университет',
                'verbose_name_plural': 'Университеты',
                'ordering': ('sort_order', 'name_ru'),
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_archived', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='В архиве')),
                ('archived_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата архивирования')),
                ('code', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='Код')),
                ('name_ru', models.CharField(max_length=255, verbose_name='Название на русском')),
                ('name_uz', models.CharField(max_length=255, verbose_name='Название на узбекском')),
                ('short_name_ru', models.CharField(blank=True, max_length=100, verbose_name='Краткое название на русском')),
                ('short_name_uz', models.CharField(blank=True, max_length=100, verbose_name='Краткое название на узбекском')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активно')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('dean_name', models.CharField(blank=True, max_length=255, verbose_name='Декан')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Электронная почта')),
                ('archived_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL, verbose_name='Архивировал')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faculties', to='organizations.university', verbose_name='Университет')),
            ],
            options={
                'verbose_name': 'Факультет',
                'verbose_name_plural': 'Факультеты',
                'ordering': ('sort_order', 'name_ru'),
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_archived', models.BooleanField(db_index=True, default=False, editable=False, verbose_name='В архиве')),
                ('archived_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата архивирования')),
                ('code', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='Код')),
                ('name_ru', models.CharField(max_length=255, verbose_name='Название на русском')),
                ('name_uz', models.CharField(max_length=255, verbose_name='Название на узбекском')),
                ('short_name_ru', models.CharField(blank=True, max_length=100, verbose_name='Краткое название на русском')),
                ('short_name_uz', models.CharField(blank=True, max_length=100, verbose_name='Краткое название на узбекском')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активно')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('head_name', models.CharField(blank=True, max_length=255, verbose_name='Заведующий кафедрой')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Электронная почта')),
                ('room', models.CharField(blank=True, max_length=100, verbose_name='Аудитория или кабинет')),
                ('archived_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_archived', to=settings.AUTH_USER_MODEL, verbose_name='Архивировал')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('updated_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Изменил')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='organizations.faculty', verbose_name='Факультет')),
            ],
            options={
                'verbose_name': 'Кафедра',
                'verbose_name_plural': 'Кафедры',
                'ordering': ('sort_order', 'name_ru'),
                'constraints': [models.UniqueConstraint(fields=('faculty', 'name_ru'), name='unique_department_name_ru_per_faculty'), models.UniqueConstraint(fields=('faculty', 'name_uz'), name='unique_department_name_uz_per_faculty')],
            },
        ),
        migrations.AddConstraint(
            model_name='faculty',
            constraint=models.UniqueConstraint(fields=('university', 'name_ru'), name='unique_faculty_name_ru_per_university'),
        ),
        migrations.AddConstraint(
            model_name='faculty',
            constraint=models.UniqueConstraint(fields=('university', 'name_uz'), name='unique_faculty_name_uz_per_university'),
        ),
    ]
