# Generated by Django 5.2.16 on 2026-07-21 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faculty',
            options={'ordering': ('sort_order', 'name_ru'), 'verbose_name': 'Факультет или отделение', 'verbose_name_plural': 'Факультеты и отделения'},
        ),
        migrations.AddField(
            model_name='faculty',
            name='faculty_type',
            field=models.CharField(choices=[('standard', 'Обычный факультет'), ('magistracy', 'Отделение магистратуры')], db_index=True, default='standard', max_length=20, verbose_name='Тип факультета'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='dean_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Декан или руководитель'),
        ),
    ]
